export const formationsWithPositions: any = {
  '4-3-3(False9)': {
    df: ['LB', 'LCB', 'RCB', 'RB'],
    cdm: ['CDM'],
    cm: ['LCM', 'RCM'],
    cam: [],
    fw: ['LW', 'CF', 'RW'],
  },
  '4-5-1(Attack)': {
    df: ['LB', 'LCB', 'RCB', 'RB'],
    cdm: [],
    cm: ['LM', 'CM', 'RM'],
    cam: ['LAM', 'RAM'],
    fw: ['ST'],
  },
  '4-1-4-1': {
    df: ['LB', 'LCB', 'RCB', 'RB'],
    cdm: ['CDM'],
    cm: [],
    cam: ['LAM', 'CAM', 'CAM', 'RAM'],
    fw: ['ST'],
  },
  '4-4-2(Flat)': {
    df: ['LB', 'LCB', 'RCB', 'RB'],
    cdm: [],
    cm: ['LM', 'LCM', 'RCM', 'RM'],
    cam: [],
    fw: ['LS', 'RS'],
  },
  '4-2-3-1(Wide)': {
    df: ['LB', 'LCB', 'RCB', 'RB'],
    cdm: ['LDM', 'RDM'],
    cm: ['LM', 'RM'],
    cam: ['CAM'],
    fw: ['ST'],
  },
  '4-4-1-1': {
    df: ['LB', 'LCB', 'RCB', 'RB'],
    cdm: [],
    cm: ['LM', 'LCM', 'RCM', 'RM'],
    cam: ['CF'],
    fw: ['ST'],
  },
  '4-5-1(Flat)': {
    df: ['LB', 'LCB', 'RCB', 'RB'],
    cdm: [],
    cm: ['LM', 'LCM', 'CM', 'RCM', 'RM'],
    cam: [],
    fw: ['ST'],
  },
  '4-1-2-1-2(Narrow)': {
    df: ['LB', 'LCB', 'RCB', 'RB'],
    cdm: ['CDM'],
    cm: ['LCM', 'RCM'],
    cam: ['CAM'],
    fw: ['LS', 'RS'],
  },
  '4-4-1-1(Midfield)': {
    df: ['LB', 'LCB', 'RCB', 'RB'],
    cdm: [],
    cm: ['LM', 'LCM', 'RCM', 'RM'],
    cam: ['CAM'],
    fw: ['ST'],
  },
  '4-1-2-1-2(Wide)': {
    df: ['LB', 'LCB', 'RCB', 'RB'],
    cdm: ['CDM'],
    cm: ['LM', 'RM'],
    cam: ['CAM'],
    fw: ['LS', 'RS'],
  },
  '4-4-2(Holding)': {
    df: ['LB', 'LCB', 'RCB', 'RB'],
    cdm: [],
    cm: ['LM', 'LCM', 'RCM', 'RM'],
    cam: [],
    fw: ['LS', 'RS'],
  },
  '4-2-2-2': {
    df: ['LB', 'LCB', 'RCB', 'RB'],
    cdm: ['LDM', 'RDM'],
    cm: [],
    cam: ['LAM', 'RAM'],
    fw: ['LS', 'RS'],
  },
  '4-3-1-2': {
    df: ['LB', 'LCB', 'RCB', 'RB'],
    cdm: [],
    cm: ['LCM', 'CM', 'RCM'],
    cam: ['CAM'],
    fw: ['LS', 'RS'],
  },
  '4-3-3(Attack)': {
    df: ['LB', 'LCB', 'RCB', 'RB'],
    cdm: [],
    cm: ['LCM', 'RCM'],
    cam: ['CAM'],
    fw: ['LW', 'ST', 'RW'],
  },
  '4-1-3-2': {
    df: ['LB', 'LCB', 'RCB', 'RB'],
    cdm: ['CDM'],
    cm: ['LM', 'CM', 'RM'],
    cam: [],
    fw: ['LS', 'RS'],
  },
  '4-3-3(Flat)': {
    df: ['LB', 'LCB', 'RCB', 'RB'],
    cdm: [],
    cm: ['LCM', 'CM', 'RCM'],
    cam: [],
    fw: ['LW', 'ST', 'RW'],
  },
  '4-3-3(Holding)': {
    df: ['LB', 'LCB', 'RCB', 'RB'],
    cdm: ['CDM'],
    cm: ['LCM', 'RCM'],
    cam: [],
    fw: ['LW', 'ST', 'RW'],
  },
  '4-3-3(Defend)': {
    df: ['LB', 'LCB', 'RCB', 'RB'],
    cdm: ['LDM', 'RDM'],
    cm: ['CM'],
    cam: [],
    fw: ['LW', 'ST', 'RW'],
  },
  '5-4-1(Diamond)': {
    df: ['LWB', 'LCB', 'CB', 'RCB', 'RWB'],
    cdm: ['CDM'],
    cm: ['LM', 'RM'],
    cam: ['CAM'],
    fw: ['ST'],
  },
  '4-2-4': {
    df: ['LB', 'LCB', 'RCB', 'RB'],
    cdm: [],
    cm: ['LCM', 'RCM'],
    cam: [],
    fw: ['LW', 'LS', 'RS', 'RW'],
  },
  '3-1-4-2': {
    df: ['LCB', 'CB', 'RCB'],
    cdm: ['CDM'],
    cm: ['LM', 'LCM', 'RCM', 'RM'],
    cam: [],
    fw: ['LS', 'RS'],
  },
  '5-4-1(Flat)': {
    df: ['LWB', 'LCB', 'CB', 'RCB', 'RWB'],
    cdm: [],
    cm: ['LM', 'LCM', 'RCM', 'RM'],
    cam: [],
    fw: ['ST'],
  },
  '3-4-1-2': {
    df: ['LCB', 'CB', 'RCB'],
    cdm: [],
    cm: ['LM', 'LCM', 'RCM', 'RM'],
    cam: ['CAM'],
    fw: ['LS', 'RS'],
  },
  '5-3-2': {
    df: ['LWB', 'LCB', 'CB', 'RCB', 'RWB'],
    cdm: [],
    cm: ['LCM', 'CM', 'RCM'],
    cam: [],
    fw: ['LS', 'RS'],
  },
  '5-2-1-2': {
    df: ['LWB', 'LCB', 'CB', 'RCB', 'RWB'],
    cdm: [],
    cm: ['LCM', 'RCM'],
    cam: ['CAM'],
    fw: ['LS', 'RS'],
  },
  '4-2-3-1(Narrow)': {
    df: ['LB', 'LCB', 'RCB', 'RB'],
    cdm: ['LDM', 'RDM'],
    cm: [],
    cam: ['LAM', 'CAM', 'RAM'],
    fw: ['ST'],
  },
  '5-2-3': {
    df: ['LWB', 'LCB', 'CB', 'RCB', 'RWB'],
    cdm: [],
    cm: ['LCM', 'RCM'],
    cam: [],
    fw: ['LW', 'ST', 'RW'],
  },
  '3-5-1-1': {
    df: ['LCB', 'CB', 'RCB'],
    cdm: ['LDM', 'RDM'],
    cm: ['LM', 'CM', 'RM'],
    cam: ['CF'],
    fw: ['ST'],
  },
  '3-5-2': {
    df: ['LCB', 'CB', 'RCB'],
    cdm: ['LDM', 'RDM'],
    cm: ['LM', 'RM'],
    cam: ['CAM'],
    fw: ['LS', 'RS'],
  },
  '3-4-3(Diamond)': {
    df: ['LCB', 'CB', 'RCB'],
    cdm: ['CDM'],
    cm: ['LM', 'RM'],
    cam: ['CAM'],
    fw: ['LW', 'ST', 'RW'],
  },
  '3-4-2-1': {
    df: ['LCB', 'CB', 'RCB'],
    cdm: [],
    cm: ['LM', 'LCM', 'RCM', 'RM'],
    cam: ['LF', 'RF'],
    fw: ['ST'],
  },
  '3-4-3(Flat)': {
    df: ['LCB', 'CB', 'RCB'],
    cdm: [],
    cm: ['LM', 'LCM', 'RCM', 'RM'],
    cam: [],
    fw: ['LW', 'ST', 'RW'],
  },
};
